### ISSUE TITLE
Error while building with CMAKE

### ISSUE THREAD

**Issue by akshit-sharma** [danielsuo/libdocker#2]
I created a new C99 project using CLion. Here I modified CMakeLists.txt and main.c files to the one given in README. Your libdocker project is in lib directory of the main project. 

I am getting 2 CMake errors:
CMake Error at CMakeLists.txt:20 (target_include_directories):
  Cannot specify include directories for target "libdocker_inte" which is not
  built by this project.
CMake Error at CMakeLists.txt:26 (target_link_libraries):
  Cannot specify link libraries for target "libdocker_inte" which is not
  built by this project.

Here's my main project's CMake file
[CMakeLists.txt](https://github.com/danielsuo/libdocker/files/823362/CMakeLists.txt)

Can you help me in determining why I might be getting this error ?

**Comment by danielsuo** [comment]
Might want to move your 'add_executable' line above where you set
target_include_directories and target_link_libraries.

**Comment by akshit-sharma** [comment]
Thank you, it build without error.

**Comment by DixitChinmay** [comment]
Still having a same error . Can you tell me the passible reason?
Thanks in advance.

**Comment by saurabheights** [comment]
@DixitChinmay  Just passing by, not a contributor to this project. The below explanation may not be 100% correct, but in gist, cmake wouldn't know how to link a library to an executable until it builds(or knows of) that executable. So move `target_link_libraries` to the last line.

```
# Link in the static library  ## <- Move linking to the end.
target_link_libraries(
        ${PROJECT_NAME}
        docker
)

set(SOURCE_FILES main.c)
add_executable(libdocker_inte ${SOURCE_FILES})
```
