### ISSUE TITLE
this sdk need libcurl version new than 7.40.0

### ISSUE THREAD

**Issue by duguhaotian** [danielsuo/libdocker#6]
src/docker.c  use "CURLOPT_UNIX_SOCKET_PATH", but this define in libcurl7.40.0.
```
void init_curl(DOCKER *client) {
  curl_easy_setopt(client->curl, CURLOPT_UNIX_SOCKET_PATH, "/var/run/docker.sock");
  curl_easy_setopt(client->curl, CURLOPT_WRITEFUNCTION, write_function);
  curl_easy_setopt(client->curl, CURLOPT_WRITEDATA, client->buffer);
}

```

more information can watch libcurl site
https://curl.haxx.se/libcurl/c/CURLOPT_UNIX_SOCKET_PATH.html

**Comment by danielsuo** [comment]
Let me know if there's something to fix. Are you suggesting we update the README? Closing for now. Feel free to re-open.
