### ISSUE TITLE
Licensing the project

### ISSUE THREAD

**Issue by osmuogar** [danielsuo/libdocker#7]
According to [github:licensing-a-repository](https://help.github.com/en/articles/licensing-a-repository)

"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project."

My intention was to use this project as a dependency for another one but since it doesn't have any explicit license I can't use it. Would you like to retain all rights or maybe some kind of open source license looks good?

**Comment by danielsuo** [comment]
Updated wit hMIT license

fixes #7

**Comment by osmuogar** [comment]
Thank you so much

**Comment by ciaran2** [comment]
Is the license reflected anywhere in the repo?

**Comment by danielsuo** [comment]
Weird. Thought I added this; mind sending PR with MIT license? Have three
under four at home and getting computer time is hard :)

**Comment by ciaran2** [comment]
This issue can probably be resolved as of https://github.com/danielsuo/libdocker/commit/740f5aebba7420b6361b393592de01a37706dd72
